accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:user_pk>/update/", views.update, name="update"),
    path("<int:user_pk>/delete/", views.delete, name="delete"),
    path("<int:user_pk>/realdelete/", views.realdelete, name="realdelete"),
    path("<int:user_pk>/user_detail/", views.user_detail, name="user_detail"),
    path("members/", views.index, name="index"),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    # path("<str:trade_pk>/", views.room, name="room"),
    path("<int:room_name>/", views.room, name="room"),
    path("<int:trade_pk>/find_room/", views.find_room, name="find_room"),
    path("init_room/", views.init_room, name="init_room"),
    path("message/", views.message, name="message"),
    path("empty/", views.message, name="message"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('reviews/', include("reviews.urls")),
    path('', include("first_view.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("index/", views.index, name="index"),
    path("<int:review_pk>/", views.detail, name="detail"),
    path("<int:review_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
    path("<int:review_pk>/comments/", views.comments, name="comments"),
    path("<int:review_pk>/join_member/", views.join_member, name="join_member"),
    path("<int:review_pk>/comments/<int:comment_pk>/delete/", views.comments_delete, name="comments_delete"),
    path("<int:game_pk>/pick_game/", views.pick_game, name="pick_game"),
    path("search/", views.search, name="search"),
]

reviews/models.py
from random import choices
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings

# Create your models here.
game = [
    (1, "덕몽어스"),
    (2, "리그 오브 레전드"),
    (3, "오버워치2"),
    (4, "어몽어스"),
    (5, "폴가이즈"),
]

header = [
    (1, "모집합니다"),
    (2, "참여합니다"),
]


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    game_name = models.IntegerField(choices=game)
    member = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(20)], default=1
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    join_member = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="join")
    header_tag = models.IntegerField(default=1)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.CharField(max_length=80)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

reviews/forms.py
from tkinter import Widget
from django import forms
from .models import Review, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("title", "game_name", "member", "content", )
        labels = {
            "title" : "제목",
            "header_tag": "말머리",
            "content" : "내용",
            "game_name" : "게임",
            "member" : "인원",
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        labels = {
            "content" : "",
        }
        widget = forms.TextInput(attrs={
                                 'placeholder': "댓글을 작성해주세요."
                                 })

reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from .models import Review, Comment
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.contrib.auth import get_user_model
from django.db.models import Q

# Create your views here.
headers = [
    (1, "모집합니다"),
    (2, "참여합니다"),
]

games = [
    "덕몽어스",
    "리그 오브 레전드",
    "오버워치2",
    "어몽어스",
    "폴가이즈",
]

@login_required
def create(request):
    if request.method == "POST":
        forms = PostForm(request.POST)
        if forms.is_valid():
            review = forms.save(commit=False)
            review.user = request.user
            review.save()
            if review.header_tag == 1:
                review.join_member.add(request.user)
                return redirect("reviews:index")
            else:
                return redirect("reviews:index")
    else:
        forms = PostForm()
    context = {
        "forms": forms,
    }
    return render(request, "reviews/create.html", context)


def index(request):
    all_data = Review.objects.order_by("-pk")
    all_user = get_user_model().objects.order_by("-pk")
    all_comment = Comment.objects.order_by("-pk")
    context = {
        "sum_data": all_data,
        "sum_user": all_user,
        "sum_comment": all_comment,
        "all_data": all_data,
        "all_user": all_user,
        "all_comment": all_comment,
    }
    return render(request, "reviews/index.html", context)



def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    header = headers[review.header_tag-1][1]
    members = review.join_member.all()
    comment_form = CommentForm()
    game = games[review.game_name-1]
    context = {
        "review": review,
        "comment_form": comment_form,
        "members": members,
        "header" : header,
        "game": game,
    }
    return render(request, "reviews/detail.html", context)

@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        forms = PostForm(request.POST, instance=review)
        if forms.is_valid():
            forms.save()
            return redirect("reviews:detail", review_pk)

    else:
        forms = PostForm(instance=review)
    context = {
        "forms": forms,
    }
    return render(request, "reviews/update.html", context)

@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if review.user == request.user:
        review.delete()
        return redirect("reviews:index")

    else:
        return HttpResponseForbidden()

@login_required
def comments(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
            return redirect("reviews:detail", review_pk)


def comments_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if comment.user == request.user:
        comment.delete()
        return redirect("reviews:detail", review_pk)
    else:
        return HttpResponseForbidden()


@login_required
def join_member(request, review_pk):
    # if request.method == "POST":
        review = get_object_or_404(Review, pk=review_pk)
        # review = Review.objects.get(pk=review_pk)
        if len(review.join_member.all()) < review.member:
            if review.join_member.filter(pk=request.user.pk).exists():
                review.join_member.remove(request.user)
            else:
                review.join_member.add(request.user)
            return redirect("reviews:detail", review_pk)
        # return HttpResponseForbidden()
        
        else:
            # 모집인원이 꽉 찼는데 이미 참여하고 있는 상태라면,
            if review.join_member.filter(pk=request.user.pk).exists():
                review.join_member.remove(request.user)
            # 메시지 처리(나중에)
            return redirect("reviews:detail", review_pk)
                
            


def pick_game(request, game_pk):
    pick_game = Review.objects.filter(game_name=game_pk)
    context = {
        "all_data": pick_game,
    }
    return render(request, "reviews/index.html", context)


def search(request):
        sum_data = Review.objects.order_by("-pk")
        sum_user = get_user_model().objects.order_by("-pk")
        sum_comment = Comment.objects.order_by("-pk")
        all_data = Review.objects.all()
        search_data = request.GET.get("search", "")

        if search_data:
            return_data = all_data.filter(
                Q(title__icontains=search_data) | Q(content__icontains=search_data)
            )
            context = {
            "sum_data": sum_data,
            "sum_user": sum_user,
            "sum_comment": sum_comment,
            "all_data" : return_data,
            }
        if len(search_data) == 0:
            none_info = "공백을 입력하셨습니다."
            context = {
                "sum_data": sum_data,
                "sum_user": sum_user,
                "sum_comment": sum_comment,
                "none_info": none_info,
            }

        elif len(return_data) == 0:
            none_info = "검색 결과가 없습니다."
            context = {
                "sum_data": sum_data,
                "sum_user": sum_user,
                "sum_comment": sum_comment,
                "none_info": none_info,
            }
        return render(request, "reviews/index.html", context)


# def update_comment(request,comment_pk,article_pk):
#     comment = Comment.objects.get(pk = comment_pk)
#     if comment.user == request.user:
#         if request.method == "POST":
#             forms = CommentForm(request.POST, instance=comment)
#             if forms.is_valid():
#                 forms.save()
#                 return redirect ("reviews:detail",article_pk)


#     return redirect("reviews:detail" ,article_pk)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% block content %}
  <form action="" method="POST" class="px-5">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-outline-primary">
  </form>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}
{% block content %}
  <div class="detail-container">
    <!-- 글 헤더(프로필, 글 제목) -->
    <div class="article-title p-1">
      <!-- 글 제목 -->
      <div class="d-flex align-items-center">
        <div class="detail-header">{{ header }}</div>
        <h1 class="detail-title text-start fw-bold">{{ review.title }}</h1>
      </div>
      <!-- 프로필 -->
      <!-- 프로필 사진 -->
      <div class="d-flex align-items-end mt-2 ms-3">
        {% if review.user.image %}
          <img src="{{ review.user.image.url }}" alt="프로필 이미지" class="detail-img border border-2">
        {% else %}
          <img src="{% static 'images/goose.png' %}" alt="프로필 대체 이미지" class="detail-img border border-2">
        {% endif %}
        <!-- 프로필 이름 -->
        <div class="d-flex flex-column justify-content-center">
          <h2 class="ms-2 fs-5 simple mb-1">{{ review.user }}</h2>
          <h2 class="ms-2 text-muted fs-6 simple">{{ review.created_at | date:"Y. m. d"}}</h2>
        </div>
      </div>
      <div>
      </div>
    </div>
    <hr>

    <!-- 글 내용 -->
    <p class="text-primary">#{{ game }}
      #{{ review.member }}명 #{{ header }}</p>
    <div class="review-content p-3 row">
      <div class="col-6 p-3">
        {{ review.content }}
      </div>
      <div class="col-6 p-5">        
        <!-- 참여자목록 -->
        <div class="container detail-box-join text-center">
          <div>
            <h2 class="mb-3">현재
              <span class="text-success">{{ members.count }}</span>
              명 참여 중</h2>
          </div>

            <!-- 방장 구역 -->
            <div class="container d-flex align-items-center">
              <!-- 프로필 사진 출력 -->
              {% if review.user.image %}
                <img src="{{ review.user.image.url }}" alt="프로필 이미지" class="detail-img">
              {% else %}
                <img src="{% static 'images/goose.png' %}" alt="프로필 대체 이미지" class="detail-img">
              {% endif %}
              <!-- 방장 이름 -->
              <h3 class="detail-user-name">방장:{{ review.user }}</h3>
              <h2 class="fw-bold">({{ members.count }}/{{ review.member }})</h2>
            </div>
            <hr>
            <!-- 참여자 구역 -->
            <div class="container overflow-auto h-100">
              {% for member in members %}
                <div class="d-flex align-items-center p-2">
                  {% if member.image %}
                    <img src="{{ member.image.url }}" alt="참가자 프로필 사진" class="detail-member-img">
                  {% else %}
                    <img src="{% static 'images/goose.png' %}" alt="프로필 대체 이미지" class="detail-member-img">
                  {% endif %}
                  <p class="mb-0 ms-2 detail-member-name">{{ member }}</p>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>

      <!-- 참여하기 버튼 -->
      <section class="my-5">
        <!-- 방장이 아닐때만 참여버튼을 출력 -->
        {% if not request.user == review.user %}
        <!-- 모집인원이 안 찼으면, -->
          {% if not members.count == review.member %}
            <a href="{% url 'reviews:join_member' review.pk %}" class="pt-btn d-flex justify-content-center">
              {% if request.user in members %}
                <div class="pt-n rounded">
                  참여취소
                </div>
              {% else %}
                <div class="pt-y rounded">
                  지금 참여하기!
                </div>
              {% endif %}
            </a>
          {% else %}
          <a href="{% url 'reviews:join_member' review.pk %}" class="pt-btn d-flex justify-content-center">
            {% if request.user in members %}
            <div class="pt-n rounded">
              참여취소
              {% else %}
              <div class="pt-y rounded">
                모집 인원이 마감되었습니다.
                {% endif %}
              </div>
            </a>
          {% endif %}
        {% endif %}
      </section>
    </div>


    <!-- 댓글 -->
    <hr>
    <h3 class="fw-bold mb-4">댓글<span class="ms-2 comment-count">{{review.comment_set.all|length }}</span></h3>
    <form action="{% url 'reviews:comments' review.pk  %}" method="POST" class="d-flex align-items-start">
      {% csrf_token %}
      <div class="w-100">
        {% bootstrap_form comment_form %}
      </div>
      <input type="submit" value="등록" class="btn btn-dark ms-2 retro">
    </form>
    <hr>
    {% for comment in review.comment_set.all %}
    <div class="container d-flex mb-5">
      <!-- 프로필 사진&라벨 영역 -->
      <div class="d-flex flex-column align-items-center">
        <div>
          {% if comment.user.image %}
          <img src="{{ comment.user.image.url }}" alt="댓글 프사" class="comment-img">
          {% else %}
          <img src="{% static '/images/none.png' %}" alt="댓글 대체 프사" class="comment-img">
          {% endif %}
        </div>
        <!-- 만약 댓글 작성한 사람이 참여중인 사람이라면 -->
        {% if comment.user in members %}
          <div class="member-label mt-2 text-center retro">
            참여 중
          </div>
          {% endif %}
        </div>
        <!-- 작성자 -->
        <div class="d-flex flex-column align-itmes-center mx-3">
          <a href="{% url 'accounts:user_detail' comment.pk  %}" class="text-decoration-none">
          <p class="comment-user"><span class="text-muted comment-how">{{ forloop.counter }} 번째 거위   </span>{{comment.user}}</p>
          </a>
          <!-- 댓글내용 -->
          <div class="comment-content">
            {{comment.content}}
          </div>
        </div>
      </div>
      <!-- 댓글 사용자가 작성자라면 수정, 삭제를 보여준다. -->
      {%if comment.user == reuqest.user %}
        <form action="{% url 'reviews:comments_delete' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="삭제">
        </form>
        <form action="{% url 'reviews:comments_update' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="수정">
        </form>
      {% endif %}
    {% endfor %}
  </div>
  {% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}
{% block content %}
  <!-- 캐러셀 -->
  <div class="text-center">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://static.inven.co.kr/column/2022/02/23/news/i14107471944.png" class="d-block w-100" alt="Duck">
        </div>
        <div class="carousel-item">
          <img src="https://i.ytimg.com/vi/m_o0MpnD7oQ/maxresdefault.jpg" class="d-block w-100" alt="OverWatch2">
        </div>
        <div class="carousel-item">
          <img src="https://i.ytimg.com/vi/8A9OGNxYyiU/maxresdefault.jpg" class="d-block w-100" alt="LOL">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <!-- 카운트 -->
    <div class="index-counter d-flex justify-content-around text-white retro">
      <div class="col-4">
        <a href="{% url 'accounts:index' %}" class="text-decoration-none text-white">
          <div class="register">
            <p class="m-0">등록한 회원 수</p>
            <h1 class="">{{ sum_user.count }}</h1>
          </div>
        </div>
      </a>
      <div class="col-4">
        <p class="m-0">작성된 글 갯수</p>
        <h1>{{ sum_data.count }}</h1>
      </div>
      <div class="col-4">
        <p class="m-0">작성된 댓글 갯수</p>
        <h1>{{ sum_comment.count }}</h1>
      </div>
    </div>

    <!-- 말풍선 -->
    <div class="info-message-div d-flex justify-content-center">
        <img src=" {% static 'images/info.png' %}">
        <div class="speech-bubble d-flex align-items-center" style="cursor: pointer;" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
          <h2 class="retro info-message">파티원을 찾아보세요!</h2>
        </div>
      </div>

    <div style="min-height: 80px;">
      <div class="collapse collapse-horizontal mx-auto" id="collapseWidthExample">
        <div class="border-0 mx-auto" style="width: 300px;">
          <form action="{% url 'reviews:search' %}">
            {% csrf_token %}
            <input type="text" class="search-bar form-control rounded-pill" placeholder="파티원을 찾아보세요." name="search">
          </form>
        </div>
      </div>
    </div>

    <div class="row row-cols-3 mx-5">
      {% for data in all_data %}
        <a href="{% url 'reviews:detail' data.pk %}" class="col index-card-a">
          <div class="index-card">
            <!-- 카드 이미지 -->
            <div>
              {% if data.game_name == 1 %}
                <img src="{% static 'images/goose.png' %}" class="index-card-img">
              {% elif data.game_name == 2 %}
                <img src="https://image.fmkorea.com/files/attach/new/20200910/14339012/2691161141/3084512844/a7a255932cf3291ee6b6fe7ffb156a2e.jpg" class="index-card-img">
              {% elif data.game_name == 3 %}
                <img src="https://static.wikia.nocookie.net/overwatch152/images/b/bf/%EC%98%A4%EB%B2%84%EC%9B%8C%EC%B9%98_%EB%A1%9C%EA%B3%A0.jpg/revision/latest?cb=20160616114533&path-prefix=ko" class="index-card-img">
              {% elif data.game_name == 4 %}
                <img src="https://img.etnews.com/photonews/2101/1379314_20210128120525_438_0001.jpg" class="index-card-img">
              {% else %}
                <img src="https://cdn2.unrealengine.com/fall-guys-is-now-free-for-all-on-the-epic-games-store-1920x1080-64479af04272.jpg" class="index-card-img">
              {% endif %}
            </div>
            <!-- 까만 텍스트 박스 -->
            <div class="index-card-content d-flex justify-content-between align-items-end">
              <div class="d-flex flex-column align-items-start">
                <div class="index-card-content-title-div">
                  <h1>{{ data.title }}</h1>
                </div>
                <h2>{{ data.user }}</h2>
              </div>
              <div class="d-flex flex-column align-items-end">
                <p class="m-0">인원</p>
                <h1>{{ data.join_member.all.count }}/{{ data.member }}</h1>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>

      <!-- 말풍선 -->
      <div class="info-message-div d-flex justify-content-center" style="margin-top: 120px;">
        <img src=" {% static 'images/info.png' %}">
        <div class="speech-bubble d-flex align-items-center" style="cursor: pointer;" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample2" aria-expanded="false" aria-controls="collapseWidthExample">
          <h2 class="retro info-message">업데이트 예정입니다.</h2>
        </div>
      </div>

    <div style="min-height: 25px;">
      <div class="collapse collapse-horizontal mx-auto" id="collapseWidthExample2">
        <div class="border-0 mx-auto" style="width: 300px;">
          <form action="{% url 'reviews:search' %}">
            {% csrf_token %}
            <input type="text" class="search-bar form-control rounded-pill" placeholder="많관부" name="search">
          </form>
        </div>
      </div>
    </div>
    <div class="text-center mb-5">
      <img src="{% static '/images/ing.png' %}"style="width: 13%;" alt="">
    </div>

  <script>
    const index_card_a = document.querySelectorAll('.index-card-a')
    for (const a of index_card_a) {
      a.addEventListener('mouseover', function () {
        for (img of index_card_a.childeren.img) {
          img.style.opacity = 1;
        }
      })
    }
  </script>
{% endblock %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-outline-primary">
  </form>
{% endblock %}