accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:user_pk>/update/", views.update, name="update"),
    path("<int:user_pk>/delete/", views.delete, name="delete"),
    path("<int:user_pk>/realdelete/", views.realdelete, name="realdelete"),
    path("<int:user_pk>/user_detail/", views.user_detail, name="user_detail"),
    path("members/", views.index, name="index"),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    # path("<str:trade_pk>/", views.room, name="room"),
    path("<int:room_name>/", views.room, name="room"),
    path("<int:trade_pk>/find_room/", views.find_room, name="find_room"),
    path("init_room/", views.init_room, name="init_room"),
    path("message/", views.message, name="message"),
    path("empty/", views.message, name="message"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('reviews/', include("reviews.urls")),
    path('', include("first_view.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("index/", views.index, name="index"),
    path("<int:review_pk>/", views.detail, name="detail"),
    path("<int:review_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
    path("<int:review_pk>/comments/", views.comments, name="comments"),
    path("<int:review_pk>/join_member/", views.join_member, name="join_member"),
    path("<int:review_pk>/comments/<int:comment_pk>/delete/", views.comments_delete, name="comments_delete"),
    path("<int:game_pk>/pick_game/", views.pick_game, name="pick_game"),
    path("search/", views.search, name="search"),
]

accounts/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    image = ProcessedImageField(
        blank=True,
        processors=[ResizeToFill(300, 300)],
        format="JPEG",
        options={"quality": 90},
    )

reviews/models.py
from random import choices
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings

# Create your models here.
game = [
    (1, "덕몽어스"),
    (2, "리그 오브 레전드"),
    (3, "오버워치2"),
    (4, "어몽어스"),
    (5, "폴가이즈"),
]

header = [
    (1, "모집합니다"),
    (2, "참여합니다"),
]


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    game_name = models.IntegerField(choices=game)
    member = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(20)], default=1
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    join_member = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="join")
    header_tag = models.IntegerField(default=1)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.CharField(max_length=80)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class MakeUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "image",
        )


class ChangeUserForm(UserChangeForm):
    password = None

    class Meta:
        model = get_user_model()
        fields = ("image", "email")

accounts/views.py
from django.shortcuts import render, redirect
from .forms import MakeUserForm, ChangeUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as my_login, logout as my_logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
def signup(request):
    if request.method == "POST":
        forms = MakeUserForm(request.POST, request.FILES)
        if forms.is_valid():
            user = forms.save()
            my_login(request, user)
            return redirect("reviews:index")
    else:
        forms = MakeUserForm()
    context = {
        "forms": forms,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            my_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {"forms": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    my_logout(request)
    return redirect("reviews:index")


@login_required
def update(request, user_pk):
    infos = get_user_model().objects.get(pk=user_pk)
    pick_user = infos
    if request.method == "POST":
        forms = ChangeUserForm(request.POST, request.FILES, instance=infos)
        if forms.is_valid():
            forms.save()
            # my_login(request, user)
            return redirect("accounts:user_detail", user_pk)
    else:
        forms = ChangeUserForm(instance=infos)
    context = {
        "forms": forms,
        'pick_user':pick_user
    }
    return render(request, "accounts/update.html", context)


@login_required
def user_detail(request, user_pk):
    pick_user = get_user_model().objects.get(pk=user_pk)
    p_page = request.GET.get("postpage")  # postpage=3
    c_page = request.GET.get("comment_page")
    if not c_page:
        status = 0
    else:
        status = 1

    user_post = pick_user.review_set.all()
    post_data = Paginator(user_post, 5)

    user_comment = pick_user.comment_set.all()
    comment_data = Paginator(user_comment, 5)

    post_page = post_data.get_page(p_page)
    comment_page = comment_data.get_page(c_page)

    context = {
        "pick_user": pick_user,
        "post_page": post_page,
        "comment_page": comment_page,
        "status": status,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def delete(request, user_pk):
    return render(request, "accounts/delete.html")


@login_required
def realdelete(request, user_pk):
    pick_user = get_user_model().objects.get(pk=user_pk)
    if pick_user.pk == request.user.pk:
        pick_user.delete()
    return redirect("reviews:index")

def index(request):
    users = get_user_model().objects.order_by("-pk")
    context = {
        "users" : users,
    }
    return render(request, "accounts/index.html", context)

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}

{% block content %}
<div class="h-100 d-flex flex-column justify-content-center align-items-center">
  <img src="{% static 'images/leave.png' %}" class="delete-img">
  <h1 class="fw-bold retro">정말 떠나시겠습니까?</h1>
  <div class="d-flex">
    <a href="{% url 'accounts:user_detail' request.user.pk %}" class="text-decoration-none text-white">
      <div class="detail-btn">아니요!!!!</div>
    </a>
    <a href="{% url 'accounts:realdelete' request.user.pk %}" class="text-decoration-none text-white">
      <div class="detail-btn" style="background-color: rgb(166, 166, 166)">네...</div>
    </a>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% block content %}
{% load static %}


<div>
    <div class="container">
        <div class="d-flex justify-content-between accounts-detail-div">
            <div class="d-flex justify-contennt-center">
                {% if pick_user.image %}
                <img class="accoutns-detail-img-div" src="{{pick_user.image.url}}" alt="pick_user.image.url">
                {% else %}
                <div>
                    <img class="accoutns-detail-img-div" src="{% static 'images/goose.png' %}" alt="pick_user.image.url"
                        height="100" width="100">
                </div>
                {% endif %}
                <div>
                    <div>
                        <p class="detail_name_id">ID : {{pick_user.username}}</p>
                        <p>email : {{pick_user.email}}</p>
                    </div>
                    <p>회원가입일:{{pick_user.date_joined}}</p>
                </div>
            </div>
            {% if request.user.pk == pick_user.pk %}
            <div class="d-flex flex-column">
                <div>
                    <a class="text-white " style="text-decoration: none;"
                        href="{% url 'accounts:update' pick_user.pk %}">
                        <div class="accounts_detail_update text-center d-flex justify-content-center">
                            <img class=" maple_icon " src="{% static 'images/maple.png' %}" alt="">
                            <p class="m-0">회원정보수정</p>
                        </div>
                    </a>
                    <a class="text-white" style="text-decoration: none;"
                        href="{% url 'accounts:delete' pick_user.pk %}">
                        <div class="accounts_detail_delete text-center">
                            <p class="m-0">회원탈퇴</p>
                        </div>
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<hr>

<!-- 유저 게시물 정보 -->
<div class="tabmenu-div">
    <div class="tabmenu">
        <ul class="d-flex justify-content-between p-0">
            <li id="tab1" class="" style="width: 450px;">
                {% if not status %}
                <input type="radio" checked name="tabmenu" id="tabmenu1">
                {% else %}
                <input type="radio" name="tabmenu" id="tabmenu1">
                {% endif %}
                <label for="tabmenu1">작성 게시물 ({{pick_user.review_set.all|length}})</label>
                <div class="tabCon">
                    <h4>{{pick_user.username}}님의 작성글</h4>
                    {% for post in post_page %}
                    <a href="{% url 'reviews:detail' post.pk %}">
                        <p>{{ post.title }}</p>
                    </a>
                    {% endfor %}
                    <!--유저 게시물 정보  페이지네이션 -->
                    <div id="paging">
                        <ul class="pagination justify-content-center" style="margin-top: 2rem;">
                            <!-- 이전페이지 -->
                            {% if post_page.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?&postpage={{ post_page.previous_page_number }}">이전</a>
                                <!-- href로 뎁스 설정 -->

                                {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                            </li>
                            {% endif %}
                            <!-- 페이지리스트 -->
                            {% for page_number in post_page.paginator.page_range %}
                            {% if page_number == post_page.number %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?&postpage={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?&postpage={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                            <!-- 다음페이지 -->
                            {% if post_page.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?&postpage={{ post_page.next_page_number }}">다음</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                    <!-- 페이징끝 -->
                </div>

                <!-- 유저 코멘트 정보 -->
            </li>
            <li id="tab2" style="width: 450px;" class="">
                <!-- {% if status == 1 %}
                <input type="radio" checked name="tabmenu" id="tabmenu1">
                {% else %}
                <input type="radio" name="tabmenu" id="tabmenu1">
                {% endif %} -->
                {% if status %}
                <input type="radio" checked name="tabmenu" id="tabmenu2">
                {% else %}
                <input type="radio" name="tabmenu" id="tabmenu2">
                {% endif %}
                <label for="tabmenu2">작성 댓글 ({{pick_user.comment_set.all|length}})</label>
                <div class="tabCon">
                    <h4>{{pick_user.username}}님의 댓글</h4>
                    {% for com in comment_page %}
                    <a href="{% url 'reviews:detail' com.review_id %}">
                        <p>{{ com.content }}</p>
                    </a>
                    {% endfor %}

                    <!--유저 게시물 정보  페이지네이션 -->
                    <div id="paging">
                        <ul class="pagination justify-content-center" style="margin-top: 2rem;">
                            <!-- 이전페이지 -->
                            {% if comment_page.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?&comment_page={{ comment_page.previous_page_number }}">이전</a>
                                <!-- href로 뎁스 설정 -->

                                {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                            </li>
                            {% endif %}
                            <!-- 페이지리스트 -->
                            {% for page_number in comment_page.paginator.page_range %}
                            {% if page_number == comment_page.number %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?&comment_page={{ page_number }}">{{page_number }}</a>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?&comment_page={{ page_number }}">{{page_number }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                            <!-- 다음페이지 -->
                            {% if comment_page.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?&comment_page={{ comment_page.next_page_number }}">다음</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                    <!-- 페이징끝 -->
                </div>
            </li>
        </ul>
    </div>
</div>









<!-- CSS -->
<style>
    * {
        margin: 0;
        padding: 0;
        font-size: 15px;
        line-height: 1.3;
    }

    ul {
        list-style: none;
    }

    .tabmenu-div {
        margin-top: 45px;
        width: 100%;
        height: 30rem;
    }

    .tabmenu {
        padding: 0 200px;
        width: 100%;
        margin: 0 auto;
        position: relative;
    }

    .tabmenu ul {
        position: relative;
    }

    .tabmenu ul li {
        display: inline-block;
        width: 33.33%;
        float: left;
        text-align: center;
        background: #f9f9f9;
        line-height: 40px;
    }

    .tabmenu label {
        display: block;
        width: 100%;
        height: 40px;
        line-height: 40px;
    }

    .tabmenu input {
        display: none;
    }

    .tabCon {
        display: none;
        width: 100%;
        text-align: left;
        padding: 20px;
        position: absolute;
        left: 0;
        top: 40px;
        box-sizing: border-box;
        border: 5px solid #f9f9f9;
    }

    .tabmenu input:checked~label {
        background: #ccc;
    }

    .tabmenu input:checked~.tabCon {
        display: block;
    }

    .accounts_detail_update {
        background: #3C6E71;
        text-decoration: none;
        width: 130px;
        height: 26px;
        border-radius: 10px;
        padding: 4px 0;
    }

    .accounts_detail_delete {
        background-color: rgb(204, 69, 69);
        text-decoration: none;
        width: 130px;
        height: 26px;
        border-radius: 10px;
        padding: 4px 0;
    }

    .maple_icon {
        width: 20px;
        height: 20px;
    }

    .accounts-detail-div {
        padding: 40px 180px;
    }

    .accoutns-detail-img-div {
        border-radius: 50%;
        width: 200px;
        height: 200px;
        margin-right: 50px;
    }


    .detail_name_id {
        font-weight: 700;
        font-size: 30px;
    }
</style>



{% endblock content %}

accounts/templates/accounts/detail_update.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% block content %}
{% load static %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="content">
    <header class="simple">
      회원 목록
    </header>
    <hr>
    <h4>사진을 누르거나 이름을 누르면 프로필 페이지로 이동합니다.</h4>
    <div class="profile-contain container">
    {% for us in users %}
      <div class="row mt-4">
        {% if us.image %}
          <a href="{% url 'accounts:user_detail' us.pk %}" class="col-2 h-25">
            <img src="{{ us.image.url }}" alt="" class="w-100 rounded-circle p-2">
          </a>
        {% else %}
          <div class="h-100 rounded-circle p-4 col-2"></div>
        {% endif %}
        <!-- 이름, 가입일 영역 -->
        <div class="col-6 d-flex flex-column align-items-start p-4">
          <a href="{% url 'accounts:user_detail' us.pk %}" class="text-decoration-none text-black">
            <p class="fs-2 fw-bold">{{ us.username }}</p>
          </a>
          <p>{{ us.date_joined }}</p>
        </div>
      </div>
      <hr>
    {% endfor %}
  </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% block content %}
  <div class="container">
    <div class="row d-flex align-items-center" style="height: 600px;">
      <div class="col-4 mx-auto">
        <h1 class="fw-bold">로그인</h1>
        <hr>
        <form action="" method="POST" class="d-flex align-items-center">
          {% csrf_token %}
          <div>
            {% bootstrap_form forms %}
          </div>
          <div>
            <input type="submit" class="login_btn btn ms-5" value="">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% block content %}
  <div class="container">
    <div class="row d-flex align-items-center" style="height: 600px;">
      <div class="col-6 mx-auto">
        <h1 class="fw-bold">회원가입</h1>
        <hr>
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div>
            <div>
              <label for="id_username" class="retro mb-3">이름을 입력하세요.</label>
              <input type="text" name="username" maxlength="150" autofocus="autofocus" class="form-control" placeholder="구스구스덕" required="required" id="id_username">
            </div>
            <div>
              <label for="id_image" class="retro mb-3">프로필 사진을 선택하세요.</label>
              <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
            </div>
            <div>
              <label for="id_password1" class="retro mb-3">비밀번호를 입력하세요.</label>
              <input type="password" name="password1" autocomplete="new-password" class="form-control" placeholder="비밀번호" required="required" id="id_password1">
            </div>
            <div>
              <label for="id_password2" class="retro mb-3">비밀번호 확인</label>
              <input type="password" name="password2" autocomplete="new-password" class="form-control" placeholder="비밀번호 확인" required="required" id="id_password2">
            </div>
          </div>
          <div class="d-flex justify-content-center mt-3">
            <input type="submit" class="d-grid btn ms-5" value="가입하기">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5%}
{% load static %}
{% block content %}
<div style="padding: 0 180px;">

  <div class="d-flex justify-content-between">
    <div class="align-items-center">
      <h1 class=" text-center accounts-update-title ">회원정보수정
      </h1>
    </div>
    <img class="accoutns-update-img-div " src="{% static 'images/shit.png' %}" alt="">
  </div>
  <hr>

  <div>
    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="d-flex justify-contennt-center">
          {% if pick_user.image %}
          <img class="accoutns-detail-img-div" src="{{pick_user.image.url}}" alt="pick_user.image.url">
          {% else %}
          <div>
            <img class="accoutns-detail-img-div" src="{% static 'images/goose.png' %}" alt="pick_user.image.url"
              height="100" width="100">
          </div>
          {% endif %}
          <div>
            <div>
              <p class="detail_name_id">ID : {{pick_user.username}}</p>
              <p>email : {{pick_user.email}}</p>
            </div>
            <p>회원가입일:{{pick_user.date_joined}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="d-flex justify-content-between">

    <img src="{% static '/images/accounts.png' %}" alt="">
  </div>
  <div>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form forms %}
      <input type="submit" class="pt-y rounded d-flex justify-content-center">
    </form>
  </div>
  <!-- 회원탈퇴 아이콘 -->
  <div class="d-flex flex-column mx-4">
    <div class="d-flex justify-content-end">
      <a class="text-white " style="text-decoration: none; " href="{% url 'accounts:delete' pick_user.pk %}">
        <div class="accounts_detail_delete text-center d-flex justify-content-center">
          <img class=" maple_icon " src="{% static 'images/exit.jpg' %}" alt="">
          <p class="m-0">회원탈퇴</p>
        </div>
      </a>
    </div>
  </div>

</div>

<style>
  .accounts_detail_update {
    background: #3C6E71;
    text-decoration: none;
    width: 130px;
    height: 26px;
    border-radius: 10px;
    padding: 4px 0;
  }

  .accounts_detail_delete {
    background-color: rgb(204, 69, 69);
    text-decoration: none;
    width: 130px;
    height: 26px;
    border-radius: 10px;
    padding: 4px 0;
  }

  .maple_icon {
    width: 20px;
    height: 20px;
  }



  .accoutns-detail-img-div {
    border-radius: 50%;
    width: 150x;
    height: 150px;
    margin-right: 30px;
  }


  .accoutns-update-img-div {
    border-radius: 25%;
    width: 100px;
    height: 100px;
    margin-right: 30px;
    margin-top: 10px;
  }

  .detail_name_id {
    font-weight: 700;
    font-size: 30px;
  }

  .accounts-update-title {
    font-size: 40px;
    margin-top: 60px;
    margin-left: 100px;
    font-weight: 700;


  }
</style>
{% endblock content %}