accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:user_pk>/update/", views.update, name="update"),
    path("<int:user_pk>/delete/", views.delete, name="delete"),
    path("<int:user_pk>/realdelete/", views.realdelete, name="realdelete"),
    path("<int:user_pk>/user_detail/", views.user_detail, name="user_detail"),
    path("members/", views.index, name="index"),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    # path("<str:trade_pk>/", views.room, name="room"),
    path("<int:room_name>/", views.room, name="room"),
    path("<int:trade_pk>/find_room/", views.find_room, name="find_room"),
    path("init_room/", views.init_room, name="init_room"),
    path("message/", views.message, name="message"),
    path("empty/", views.message, name="message"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('reviews/', include("reviews.urls")),
    path('', include("first_view.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("index/", views.index, name="index"),
    path("<int:review_pk>/", views.detail, name="detail"),
    path("<int:review_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
    path("<int:review_pk>/comments/", views.comments, name="comments"),
    path("<int:review_pk>/join_member/", views.join_member, name="join_member"),
    path("<int:review_pk>/comments/<int:comment_pk>/delete/", views.comments_delete, name="comments_delete"),
    path("<int:game_pk>/pick_game/", views.pick_game, name="pick_game"),
    path("search/", views.search, name="search"),
]

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body class="bg">
    <!-- 네브바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light retro">
      <div class="container">
        <a class="navbar-brand" href="#">보류</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-flex justify-content-between collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'reviews:index' %}">홈</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reviews:create' %}">파티찾기</a>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_detail' request.user.pk %}">마이 페이지</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
            </ul>
          {% else %}
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>
            </ul>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container simple base-contents">
      {% block content %}{% endblock content %}
      {% bootstrap_javascript %}
    </div>
  </body>

</html>